language: perl
perl:
  - "5.34"
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.34-shrplib"
  - "5.32-shrplib"
  - "5.30-shrplib"
  - "5.28-shrplib"
  - "5.26-shrplib"
  - "5.24-shrplib"
  - "5.22-shrplib"
notifications:
  email:
    recipients:
      - jkeenan@cpan.org
    on_success: never
    on_failure: always
matrix:
  allow_failures:
    - perl: blead
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
